// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkSNGQjppTSDM3qqUQKnwA1qrpZc3Ztv8',
    appId: '1:829191611648:web:dd61bdb0bc8c5755a77fe5',
    messagingSenderId: '829191611648',
    projectId: 'foodgo-2dce6',
    authDomain: 'foodgo-2dce6.firebaseapp.com',
    storageBucket: 'foodgo-2dce6.firebasestorage.app',
    measurementId: 'G-TBMGQS67QH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPiJc7vnQKiW_-5GbhKorKNraS4xnugCQ',
    appId: '1:829191611648:android:ea3fe494dd80d221a77fe5',
    messagingSenderId: '829191611648',
    projectId: 'foodgo-2dce6',
    storageBucket: 'foodgo-2dce6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZe2VmRHraAttKUuDGLuM7uGJdUrGOczE',
    appId: '1:829191611648:ios:6b8ce0fa1be05c6ba77fe5',
    messagingSenderId: '829191611648',
    projectId: 'foodgo-2dce6',
    storageBucket: 'foodgo-2dce6.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp8sc2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZe2VmRHraAttKUuDGLuM7uGJdUrGOczE',
    appId: '1:829191611648:ios:6b8ce0fa1be05c6ba77fe5',
    messagingSenderId: '829191611648',
    projectId: 'foodgo-2dce6',
    storageBucket: 'foodgo-2dce6.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp8sc2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkSNGQjppTSDM3qqUQKnwA1qrpZc3Ztv8',
    appId: '1:829191611648:web:9d83d4eafa47943ca77fe5',
    messagingSenderId: '829191611648',
    projectId: 'foodgo-2dce6',
    authDomain: 'foodgo-2dce6.firebaseapp.com',
    storageBucket: 'foodgo-2dce6.firebasestorage.app',
    measurementId: 'G-QGN698FVE1',
  );
}
